odom_frame: odom
base_link_frame: chassis
world_frame: odom

two_d_mode: true

frequency: 50

odom0: odometry
odom0_config: [true, true, true,
               false, false, true,
               true, true, false,
               false, false, true,
               false, false, false]
odom0_differential: false
odom0_queue_size: 10

imu0: imu/data
imu0_config: [false, false, false,
              true, true, true,
              false, false, false,
              true, true, true,
              true, true, true]
imu0_differential: false
imu0_queue_size: 10
imu0_remove_gravitational_acceleration: true
